### ISSUE TITLE
在新建activity的时候能否指定路径?

### ISSUE THREAD

**Issue by H-Zan** [EastWoodYang/MicroModule#1]
在新建activity的时候能否指定路径? 现在新建Activity会自动创建到p_base下面

**Comment by EastWoodYang** [comment]
新建activity？是新建class吗？新建class在对应的包名上右击新建？

**Comment by EastWoodYang** [comment]
我知道你说的新建activity了，新建activity指定路径需要开发相关的IDE插件了。
目前暂时先不考虑，抱歉了。

**Comment by H-Zan** [comment]
好的,谢谢
