### ISSUE TITLE
pins工程之间怎么通信？

### ISSUE THREAD

**Issue by RFlame** [EastWoodYang/MicroModule#10]
pins工程之间怎么通信方便一点？可以使用Arouter么

**Comment by EastWoodYang** [comment]
MicroModule只是在传统的android模块中重新构建出多个类似于原有模块的工程结构，属于工程结构范畴。原先模块怎么通信。现在就怎么通信呗。

另外本人观点，arouter偏向于单向通信，应该作为简单的路由组件，而模块间通信应该选用双向通信，比如接口方案。

**Comment by EastWoodYang** [comment]
还是什么问题的话可以直接加我微信，Lord-with-us，首页上也有微信号展示。
