### ISSUE TITLE
MicroMoudle生成的R文件缺少mipmap资源引用

### ISSUE THREAD

**Issue by WwhOS** [EastWoodYang/MicroModule#12]
class GenerateMicroModuleRFileTask extends DefaultTask {

    public final static List<String> SUPPORT_RESOURCE_TYPE = ["anim", "array", "attr", "bool", "color", "dimen",
                                                              "drawable", "id", "integer", "layout", "menu", "plurals", "string", "style", "styleable"]

**Comment by EastWoodYang** [comment]
感谢指正

**Comment by EastWoodYang** [comment]
这个问题已在v1.3.2中修复
