### ISSUE TITLE
运行提示找不到Activity Could not identify launch activity: Default Activity not found

### ISSUE THREAD

**Issue by BigBigDeBoy** [EastWoodYang/MicroModule#14]
<img width="1232" alt="图片" src="https://user-images.githubusercontent.com/16618853/84847661-2ddf4500-b084-11ea-936f-9ec01270a2df.png">

**Comment by YangKee** [comment]
我也遇到了同样的问题，请问有找到解决方案吗

**Comment by EastWoodYang** [comment]
在AS 4.0上确实会出现这个问题，差不多的问题 可以移步 https://issuetracker.google.com/issues/158019870#comment28.
该问题已经在AS 4.1上修复。
如果 你要在AS 4.0上使用的话，可以建议你Application模块不要使用MicroModule，在library模块使用。
