### ISSUE TITLE
microModuleReferenceMap's mulit initialization will lost most of dependencies info when multi module apply plugins

### ISSUE THREAD

**Issue by LiesSu** [EastWoodYang/MicroModule#3]
microModuleReferenceMap's mulit initialization will lost most of dependencies info when multi module apply plugins

ex. module A and B apply plugins
1.  module A into afterEvaluate, initialize microModuleReferenceMap and put [base3:base1, base3:base1]
2. module B into afterEvaluate, reinitialize microModuleReferenceMap, then info [base3:base1, base3:base1]
 lost

**Comment by EastWoodYang** [comment]
非常感谢提出这个问题，其实并不影响实际检测机制。
因为microModuleReferenceMap在MicroModulePlugin中初始化后，被MicroModuleCodeCheckPlugin引用。之后再初始化时，MicroModulePlugin中microModuleReferenceMap指向新的地址空间，MicroModuleCodeCheckPlugin中的microModuleReferenceMap还是指向之前的地址空间。

**Comment by EastWoodYang** [comment]
这个有点不合理的方式，我已经在v.1.1.0中优化了。

再次表示感谢 ;-)
