### ISSUE TITLE
插件源码添加MicroModule资源过程重复了？

### ISSUE THREAD

**Issue by zuowenpin** [EastWoodYang/MicroModule#7]
你好，我看源码的时候，发现在afterEvaluate过程中，会将MicroModule的addMicroModuleSourceSet添加一次，在preBuild Task中，又会添加一次addMicroModuleSourceSet是重复了吗？
我这边将preBuild Task中去掉后，也能正常编译，是考虑到Gradle版本兼容性的问题吗？

非常感谢~

**Comment by EastWoodYang** [comment]
不是兼容性，你可以尝试下 去掉，然后执行‘rebuild’，你就知道原因了 :-)

**Comment by zuowenpin** [comment]
我这边去掉了preBuild, rebuild也没有异常，通过看Build过程，> Configure project :microsystem 会正常执行到，microsystem是我这边使用了microsystem插件的一个library工程, 最终apk的代码也没有什么异常.   Gradle gradle-4.10.1-all.zip  android plugin com.android.tools.build:gradle:3.2.1.

**Comment by EastWoodYang** [comment]
你是在我demo上跑的吗？

**Comment by EastWoodYang** [comment]
注释掉 project.tasks.preBuild.doFirst，会报
* What went wrong:
Execution failed for task ':library:checkDebugManifest'.
> Main Manifest missing for variant debug
异常

**Comment by EastWoodYang** [comment]
原因是 在gradle configure时期会生成并设置模块的AndroidManifest,xml，但在execute时期，有可能执行clean Task 清除了之前configure时期生成的AndroidManifest,xml，为避免这种情况，在模块prebuild前重新生成AndroidManifest,xml。

**Comment by EastWoodYang** [comment]
生成Androidmanifest.xml是要基于java和res的，所以还是要重新设置sourceSets的

**Comment by zuowenpin** [comment]
非常感谢~ 我再学习下生成AndroidManifest的过程~ 另外R.java的处理感觉有点复杂，直接使用Module的R.java不好吗，另外我这边Studio会变红，编译是正常的.
![default](https://user-images.githubusercontent.com/11957823/52039110-9d779180-256e-11e9-95ca-109a113c34a9.png)

**Comment by EastWoodYang** [comment]
R类就涉及到兼容性问题了。。。

变红的话，试试 sync clean rebuild 或重新打开AS....
