### ISSUE TITLE
Cannot get property 'microModuleDir' on null object

### ISSUE THREAD

**Issue by RFlame** [EastWoodYang/MicroModule#8]
Android studio 3.3 按照使用步骤配置，出现Cannot get property 'microModuleDir' on null object，请问是哪里不对吗

**Comment by RFlame** [comment]
切换成gradle3.3.0就没问题，3.3.1有问题

**Comment by EastWoodYang** [comment]
完整的日志能贴出来吗？
deme 工程 gradle 3.3.1没复现出这个问题，或者你可以试试demo工程

**Comment by RFlame** [comment]
目前又好了，再出现了再反馈下，多谢
